# Site settings
title: 제이키의 MVC 이야기
email: jake@jakeymvc.com
description: > # this means to ignore newlines until "baseurl:"
  웹 개발을 즐겁게 만들어준 ASP.NET MVC와 ASP.NET 5의 변화를 이야하기하는 블로그 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.jakeymvc.com" # the base hostname & protocol for your site
#twitter_username: jakeryu  # if defined, it appears in the footer 
github_username: "jakeymvc" 
timezone: Europe/London
permalink: pretty
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Build settings
markdown: redcarpet
