# Site settings
title: 제이키의 MVC 이야기
email: jakeymvc@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  웹 개발을 즐겁게 만들어준 ASP.NET MVC 와  기대 가득한 ASP.NET 5를 이야하기하는 블로그 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jakeymvc.github.io" # the base hostname & protocol for your site
#twitter_username: jakeryu  # if defined, it appears in the footer 
github_username:  jakeymvc
timezone: Europe/London
permalink: pretty
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Build settings
markdown: redcarpet
